AWSTemplateFormatVersion: "2010-09-09"
Description: "AI Career Agent - Minimal Working Infrastructure"

Resources:
  # Simple S3 Bucket
  CareerAgentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "ai-career-agent-${AWS::AccountId}"

  # Simple Lambda Function
  CareerAgentFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "ai-career-agent-demo"
      Runtime: python3.11
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('AI Career Agent is working!')
              }
      Role: !GetAtt LambdaRole.Arn

  # IAM Role for Lambda
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  BucketName:
    Value: !Ref CareerAgentBucket
  FunctionName:
    Value: !Ref CareerAgentFunction
