[server]
port = 8501
address = "0.0.0.0"
headless = true

[theme]
primaryColor = "#0593A2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#151F30"

[browser]
gatherUsageStats = false